### PR TITLE
Image processing optimizations

### PR DESCRIPTION
**Pull request by tbeck**
@lsdrew / @samyue888 
Here are the optimization changes for image processing. Here is a summary of the scores when testing locally. (No Google Tag Manager influence)

[Librestream_LHR_desktop.pdf](https://github.com/ocupop/librestream/files/6367387/Librestream_LHR_desktop.pdf)

### CODE REVIEW

**Comment by samyue888** [comment]
Thanks @tbeck 
I'm checking the mobile speed test and it says that we can save ~15s by optimizing the banner images. Are these accounted for in this branch? 
image

**Comment by tbeck** [comment]
@samyue888 
Yes... the image handling and processing are part of this PR.

**Comment by tbeck** [comment]
Looks like the initial PR build failed because of a timeout (large files). I re-triggered it manually and here is the success:
https://www.gatsbyjs.com/dashboard/dc5c64f1-456d-477f-baa4-7d974a20c9a4/sites/994efcf0-b7bb-4e52-a215-cb1fbb0d7300/builds/cedff40b-d378-4afd-bd04-564287f010c9/details

**Comment by tbeck** [comment]
@lsdrew - Can you merge this PR?

**Comment by samyue888** [comment]
@tbeck Hi Tom, could you please give me permission to merge as well? Thanks

CC @lsdrew

**Comment by tbeck** [comment]
@samyue888 - You should already have permissions to merge pull request. Let me know if you are not seeing this on your end: https://gyazo.com/0818813d7a0d967539cc65e46030c2a5

**Comment by samyue888** [comment]
@tbeck Nope, I only see this: 
image

**Comment by tbeck** [comment]
@samyue888 - Your role has been updated to admin. You should be able to merge PRs now.

Thanks!

**Comment by samyue888** [comment]
@tbeck @lsdrew After merge, I'm getting this flag in the Gatsby build. How shall we address this?
image

**Comment by samyue888** [comment]
Also @tbeck after merging, the speed test scores did not improve. Are you able to pinpoint the issue?
image
image

**Pull request merged**
